services:
  database:
      logging:
        driver: none
      image: mongo:3.4.6
      ports:
          - "27019:27017"
      environment:
          - MONGODB_DATABASE="libreflix"
          - MONGODB_USER="libreflix"
          - MONGODB_PASS="PASSWORD"

  libreflix:
      stdin_open: true
      build: .
      volumes:
        - ./:/libreflix
        - /libreflix/node_modules
      command: make start
      ports:
        - "3998:3998"
      links:
        - database
